name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev

env:
  SERVER_HOST: 37.140.192.111
  SERVER_USER: u2309053
  SERVER_PORT: 22
  SERVER_PATH: /var/www/u2309053/voronov-project.ru

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          port: ${{ env.SERVER_PORT }}
          key: ${{ secrets.SSHKEY }}
          password: ${{ secrets.PASSWORD }}
          passphrase: ${{secrets.PHRASE}}
          script: "cd ${{env.SERVER_PATH}} && ./.scripts/deploy.sh"
